### ISSUE TITLE
#TODO

### ISSUE THREAD

**Issue by yitong-ovo** [yitong-ovo/web-port-knocking#1]
- [ ] 分离权限，比如 https://github.com/moxie0/knockknock 这样的，让执行 iptables 和 api 分离
    - [ ] @ReimuNotMoe 的建议: 写 /dev/ttyprintk 读 /proc/kmsg < 但读取 kmsg 可能在容器里被限制。
- [x] requirements.txt
- [x] systemd + wsgi 配置文件
- [ ] wsgi 配置教程
- [x] 测试反向代理下的可用性
